
	$(document).ready(function(){
	//Matrix of First selection of the first dropdown
		$("#option1").click(function(){
			$(".tpgPerPhaseBtn").show();
			$("#firstDiv").show();		
		});
		$("#option4").click(function(){			
			$("#fourthDiv").show();
			$("#fifthDiv").hide();
			$("#seventhDiv").hide();
		});
		$("#option6").click(function(){						
			$("#fourthDiv").hide();
			$("#fifthDiv").show();
			$("#seventhDiv").hide();
		});
		$("#option7").click(function(){			
			$("#fourthDiv").hide();
			$("#fifthDiv").hide();
			$("#seventhDiv").show();			
		});
		$("#option5").click(function(){			
			$("#fifthDiv").show();
			$("#fourthDiv").hide();
			$("#seventhDiv").hide();
		});
		$("#option5").click(function(){			
			$("#fifthDiv").show();
			$("#fourthDiv").hide();
			$("#seventhDiv").hide();
		});
		$("#option4,#option5,#option6,#option7").click(function(){			
			$(".bundledConductorBtn").show();
		});
		$("#option8,#option9").click(function(){			
			$(".preJobBtn").show();
		});
		$("#option8").click(function(){			
			$("#bundledConductorYes").show();
			$("#bundledConductorNo").hide();
		});
		$("#option9").click(function(){				
			$("#bundledConductorNo").show();
			$("#bundledConductorYes").hide();
		});
		$("#option10").click(function(){				
			$("#preJobYes").show();
			$("#preJobNo").hide();
			$(".clearanceBtn").show();
		});
		$("#option11").click(function(){				
			$("#preJobNo").show();
			$("#preJobYes").hide();
			$(".clearanceBtn").hide();
		});
		$("#option12").click(function(){				
			$("#clearenceYes").show();
			$("#clearenceNo").hide();
			$(".switchBtn").show();
		});
		$("#option13").click(function(){				
			$("#clearenceNo").show();
			$("#clearenceYes").hide();
			$(".switchBtn").show();
		});
		$("#option14").click(function(){				
			$("#switchYes").show();
			$("#switchNo").hide();
			$(".workSiteBtn").show();
		});
		$("#option15").click(function(){				
			$("#switchNo").show();
			$("#switchYes").show();
			$(".workSiteBtn").show();
		});
		$("#option16").click(function(){				
			$("#workSiteYes").show();
			$("#workSiteNo").hide();
		});
		$("#option17").click(function(){				
			$("#workSiteNo").show();
			$("#workSiteYes").hide();
		});
		//changes the dropdown text for Circuit Breaker tree
		 $('#option1').click(function(){		 
		 $('#change1').text($(this).text());
			});
		$('#option4,#option5,#option6,#option7').click(function(){		 
		 $('#change2').text($(this).text());
			});	
		$('#option8,#option9').click(function(){		 
		 $('#change3').text($(this).text());
			});	
		$('#option10,#option11').click(function(){		 
		 $('#change4').text($(this).text());
			});
		$('#option12,#option13').click(function(){		 
		 $('#change5').text($(this).text());
			});
		$('#option14,#option15').click(function(){		 
		 $('#change6').text($(this).text());
			});
		$('#option16,#option17').click(function(){		 
		 $('#change7').text($(this).text());
			});
	});
